version: 0.0
os: linux

files:
  - source: /  # This specifies the source directory in the repository. This can be adjusted if you're packaging specific files.
    destination: /home/ec2-user/musician-app/  # Destination directory on the EC2 instance.

hooks:
  BeforeInstall:
    - location: stop_server.sh  # Stops the application or other processes before installing new versions.
      timeout: 300
      runas: ec2-user  # Run the script as the ec2-user

  AfterInstall:
    - location: install_dependencies.sh  # Install dependencies after the code is deployed.
      timeout: 300
      runas: ec2-user  # Run the script as the ec2-user

  ApplicationStart:
    - location: start_server.sh  # Starts the application after dependencies are installed.
      timeout: 300
      runas: ec2-user  # Run the script as the ec2-user
