version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18  # Make sure the correct Node.js version is used
    commands:
      - echo "Installing dependencies..."
      - npm install
  build:
    commands:
      - echo "Building the application..."
      - NODE_ENV=production npm run build
artifacts:
  files:
    - '**/*'
  discard-paths: yes
