version: 0.2

phases:
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - dnf npm install
  build:
    commands:
      - echo "Building the application..."
      - NODE_ENV=production dnf npm run build
artifacts:
  files:
    - '**/*'
  discard-paths: yes
