version: 0.2

phases:
  pre_build:
    commands:
      - echo "Starting pre-build phase..."
      - npm install
  build:
    commands:
      - echo "Building the application..."
      - npm run build
artifacts:
  files:
    - '**/*'
  discard-paths: yes

